### ISSUE TITLE
Julia 1.5.0-beta is set as the kernel

### ISSUE THREAD

**Issue by onButtonUp** [dpsanders/LearnJulia2020#1]
The readme file indicates "install the latest release (1.4.2) of Julia". The notebooks open looking for 1.5.0-beta.

**Comment by dpsanders** [comment]
Hmm good point, thanks. So it prompts you to select a ~version~ kernel?

**Comment by dpsanders** [comment]
I changed to 1.4.2 -- could you please check that it works OK? Thanks!

**Comment by onButtonUp** [comment]
Looks like the same file. It says it was uploaded an hour ago. So no change. At the bottom of the *.ipynb files it shows

  "language_info": {
   "file_extension": ".jl",
   "mimetype": "application/julia",
   "name": "julia",
   "version": "1.5.0"


And, yes, it does ask to select another kernel. (I selected 1.4.2 and they work).

**Comment by onButtonUp** [comment]
<img width="1048" alt="001" src="https://user-images.githubusercontent.com/7108393/88356077-7e992c00-cd1b-11ea-9573-a098a87eac2e.png">

**Comment by dpsanders** [comment]
Apologies, should be fixed now.

**Comment by onButtonUp** [comment]
Perfect! Thank you, David !

**Comment by dpsanders** [comment]
That is strange.

**Comment by dpsanders** [comment]
Thanks a lot for pointing it out!
